name: Build Linux

on:
    pull_request:
        branches: [Roblox.SiteTest4]
    push:
        branches: [Roblox.SiteTest4]
    schedule:
        - cron: '*/30 * * * *'

jobs:
    BuildLinux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npm run build-full
